/* eslint-disable no-unused-vars */


// eslint-disable-next-line no-unused-vars
import Code1 from "./Code1";
import Code2 from "./Code2";
import Code3 from "./Code3";
import Code4 from "./Code4";
import Code5 from "./Code5";
import Code6 from "./Code6";
import Code7 from "./Code7";
import Code8 from "./Code8";
import Code9 from "./Code9";
import Code10 from "./Code10";
import Prototype from "./Code12";
import CallbacksInjavascript from "./Code13";
import CallandApplly from "./Code14";
import Genarators from "./Code15";
import Reducemethod from "./Code16";
import Usecallbackhook from "./Code17";
import Callbacks from "./Code18";
import { Exporetedhoc } from "./Code19";
import ParentComponentCustomhooks from "./Code20";
import Childtoparent from "./Code21";
import Childtoparent1 from "./Code22";
import Code23 from "./Code23";
import Reversestring from "./Code24";
import Removeduplicates from "./Code25";
import SumofAllelElement from "./Code26";
import Largestelement from "./Code27";
import IsarraySorted from "./Code28";
import Concatestring from "./Code29";
import MergeArray from "./Code30";
import Findindex from "./Code31";
import FlattenArray from "./Code32";
import FindSumofgivenarray from "./Code33";
import Secondlargestelement from "./Code35";
import SortObject from "./Code36";
import MissingNumber from "./Code37";
import MultipleApis from "./Code38";
import Copyconcept from "./Code40";
import Objectproblems from "./Code41";
import Recurrsion from "./Code42";
import BalancedParenthesis from "./Code43";
import PaginatedList from "./Code44";
import Formvalidations from "./Code45";
import ListTransfer from "./Code46";
import Createprogressbar from "./Code47";
import Simpleproblems from "./Code48";
import Removewhitespaces from "./Code49";
import Factorial from "./Code50";
import Primenumberornot from "./Code51";
import LargestNumberinarray from "./Code53";
import Vovelproblemms from "./Code54";
import Anagram from "./Code55";
import Duplicateremove from "./Code56";
import Longerswors from "./Code57";
import Counterinreact from "./Code60";
import Avoiduseeffect from "./Code61";
import Checkingdataproblems from "./Code62";
import Passwordinput from "./Code63";
import Findminmax from "./Code64";
import Code65 from "./Code65";
import Code66 from "./Code66";
import Code67 from './Code67';
import Printtable from "./Code68";
import Convertletter from "./Code69";
import Code70 from "./Code70";
import MainComponenet from "./Code71";
import UseCustohook from "./Code72";
import Fakesteoreapis from "./Code73";
import UseCustomHook1 from "./Code73";
import Mainhoc from "./Code74";
import Grid from "./Code75";
import Addbucket from "./Code76";
import Deletefromaray from "./Code78";
import Updatearray from "./Code79";
import Code80 from "./Code80";
import Dom1 from "./Code81";
import Curringjavascript from "./Code82";
import Dom2 from "./Code83";
import Lifecycles from "./Code84";
import Constrution from "./Code85";
import Promisesinjavascript from "./Code87";
import Pagetravel from "./Code90";
import Newconcepts from "./Code91";
import OuterComponent from "./Code92";
import PowerClosures from "./Code93";
import Foreachcase from "./Code94";
import Switchstatement from "./Code95";
import Handlepromises from "./Code96";
import Code97 from "./Code97";
import CurrrancyConvert from "./Code98";
import Nestedobject from "./Code100";
import Searchbarcomponent from "./Code101";
import SelectionInTable from "./Code102";
import Avoidchildrender from "./Code103";
import Parent from "./Code105";
import MyComponent from "./Code106";
import App1 from "./Code107";
import Code108 from "./Code108";
import CodeExample from "./Code109";
import Promisesundersyanding from "./Code111";
import Mainfolder from "./Code112";
import MainFolder1 from "./Coder113";
import Experiments from "./Code113";
import Experimets1 from "./Code114";
import Code115 from "./Code115";
import Code116 from "./Code116";
import Code117 from "./Code117";
import Code118 from "./Code118";
import Code119 from "./Code119";
import Timercode from "./Code120";
import Printdatadisplay from "./Code121";
import Code122 from "./Code122";
import Code123 from "./Code123";
import Code124 from "./Code124";
import Counterproblem from "./Code125";
import Code126 from "./Code126";
import Code128 from "./Code128";
// import Contextforname from "./Code129";
// import Code130 from "./Code130";
import Closures from "./Code131";
import Curring from "./Code132";
import Code133 from "./Code133";
import Code134 from "./Code134";
import Callbacks1 from "./Code136";
import Code137 from "./Code137";
// import Code137 from "./Code137";
import CounterP from "./Code140";
import Code141 from './Code141';
import Code142 from './Code142'
import Code143 from "./Code143";
import Fetch2 from "./Fetch2";
import Pagination from "./Paginations";
import Form1 from "./Form/Form1";
import Code148 from "./Form/Code148";
import Hoc222 from "./Form/Hoc222";
import Code223 from "./Code223";
import Code150 from "./Code150";
import Code152 from "./Code152";
import Code153 from "./Code153";
import Code154 from "./Code154";
import Code155 from "./Code155";
import { Hocsend } from "./Code156";
import Printdata from "./Code157";
import Code158 from "./Code158";
import Code159 from "./Code159";
import Code160 from "./Code160";
import Code161 from "./Code161";
import Code162 from "./Code162";
import Code163 from "./Code163";
import Code164 from "./Code164";
import Code165 from "./Code165";
function App() {
  return (
    <div>
       <Code165/>
    </div>
  );
}

export default App;
